In [2]:
import pandas as pd
df = pd.read_csv('disabled-driving-licence-data.csv',encoding='latin-1')
df['Year'] = df['Year'].astype(str)
df['Full car driving licence'] = df['Full car driving licence'].str.replace(',', '').astype(int)
df['All people'] = df['All people'].str.replace(',','').astype(int)
df['Unweighted sample size: individuals [notes 4, 5]'] = df['Unweighted sample size: individuals [notes 4, 5]'].str.replace(',','').astype(int)

In [3]:
df.style.background_gradient(cmap='PuBu')

In [4]:
nonDis = df.where(df['Disability status'] == 'Not disabled').dropna()

In [5]:
nonDis.style.background_gradient(cmap='RdPu')

In [9]:
disDF = df.where(df['Disability status'] == 'Disabled').dropna()

In [10]:
disDF.style.background_gradient(cmap='RdPu')